lib/pan_web/router.ex
    get("/podcasts/search", PodcastController, :search)
    get("/podcasts/most_subscribed", PodcastController, :most_subscribed)
    get("/podcasts/most_liked", PodcastController, :most_liked)
    get("/podcasts/last_updated", PodcastController, :last_updated)
    resources("/podcasts", PodcastController, only: [:index, :show])

    resources("/likes", LikeController, only: [:show])
    resources("/follows", FollowController, only: [:show])
    resources("/subscriptions", SubscriptionController, only: [:show])

    post("/login", SessionController, :login)
    post("/get_token", SessionController, :login)
  end

  scope "/jsonapi/pan", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_user])

    post("/likes/toggle", LikeController, :toggle)
    post("/follows/toggle", FollowController, :toggle)
    post("/subscriptions/toggle", SubscriptionController, :toggle)
    post("/gigs/toggle", GigController, :toggle)

    resources("/recommendations", RecommendationController, only: [:create])
    get("/recommendations/my", RecommendationController, :my)

    get("/podcasts/:id/trigger_update", PodcastController, :trigger_update)
    get("/podcasts/:id/trigger_episode_update", PodcastController, :trigger_episode_update)

    get("/podcasts/i_follow", PodcastController, :i_follow)
    get("/podcasts/i_like", PodcastController, :i_like)
    get("/podcasts/i_subscribed", PodcastController, :i_subscribed)
    get("/podcasts/also_listened_to", PodcastController, :also_listened_to)
    get("/podcasts/also_liked", PodcastController, :also_liked)

    get("/categories/my", CategoryController, :my)
    post("/like_all_subscribed_podcasts", LikeController, :like_all_subscribed_podcasts)
    post("/follow_all_subscribed_podcasts", FollowController, :follow_all_subscribed_podcasts)

    get("/opmls/:id/import", OpmlController, :import)
    resources("/opmls", OpmlController, only: [:index, :show, :create, :delete])

    resources("/feed_backlogs", FeedBacklogController, only: [:show, :create])

    get("/users/my", UserController, :my)

    patch("/update_password", UserController, :update_password)
    put("/update_password", UserController, :update_password)
    patch("/update_user", UserController, :update_user)
    put("/update_user", UserController, :update_user)

    post("/personas/:id/claim", PersonaController, :claim)
    resources("/personas", PersonaController, only: [:update])

    resources("/delegations", DelegationController, only: [:show])
  end

  scope "/jsonapi/pro", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_pro_user])

    post("/personas/:id/redirect", PersonaController, :redirect)
    post("/personas/:id/cancel_redirect", PersonaController, :cancel_redirect)
    put("/personas/:id", PersonaController, :pro_update)
    patch("/personas/:id", PersonaController, :pro_update)

    post("/delegations/toggle", DelegationController, :toggle)
  end

  scope "/jsonapi/moderator", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_moderator])
    # no moderator specific api routes defined yet
  end

  scope "/bot", PanWeb do
    pipe_through(:bot)

    get("/webhook", BotController, :webhook)
    post("/webhook", BotController, :message)
  end

  scope "/search", PanWeb do
    pipe_through([:browser])

    post("/", SearchFrontendController, :new)
    live("/:index/:term", Live.Search, :search, as: :search_frontend)
  end

  live_session :admin, on_mount: {PanWeb.Live.Auth, :admin} do
    scope "/admin", PanWeb do
      pipe_through([:browser, :authenticate_admin, :admin_layout])
      live("/", Live.Admin.Dashboard, :home, as: :dashboard)
      live("/sandbox", Live.Admin.Sandbox, :home, as: :sandbox)

      live("/databrowser/:resource", Live.Admin.Databrowser.Index, :index, as: :databrowser)

      live("/databrowser/:resource/db_indices", Live.Admin.Databrowser.DbIndex, :db_indices,
        as: :databrowser
      )

      live(
        "/databrowser/:resource/schema_definition",
        Live.Admin.Databrowser.SchemaDefinition,
        :schema_definition,
        as: :databrowser
      )

      live("/databrowser/:resource/new", Live.Admin.Databrowser.New, :new, as: :databrowser)
      live("/databrowser/:resource/:id", Live.Admin.Databrowser.Show, :show, as: :databrowser)

      live("/databrowser/:resource/:id/edit", Live.Admin.Databrowser.Edit, :edit,
        as: :databrowser
      )

      live(
        "/databrowser/:resource/new/:first_column/:first_id/:second_column/:second_id",
        Live.Admin.Databrowser.NewAssociation,
        :new_association,
        as: :databrowser
      )

      live(
        "/databrowser/:owner/:owner_id/has_many/:association",
        Live.Admin.Databrowser.HasMany,
        :has_many,
        as: :databrowser
      )

      live(
        "/databrowser/:owner/:owner_id/many_to_many/:association",
        Live.Admin.Databrowser.ManyToMany,
        :many_to_many,
        as: :databrowser
      )

      live(
        "/databrowser/show_mediating/:resource/:first_column/:first_id/:second_column/:second_id/id",
        Live.Admin.Databrowser.ShowMediating,
        :show_mediating,
        as: :databrowser
      )

      live(
        "/databrowser/edit_mediating/:resource/:first_column/:first_id/:second_column/:second_id/id",
        Live.Admin.Databrowser.EditMediating,
        :edit_mediating,
        as: :databrowser
      )
    end
  end

  scope "/", PanWeb do
    pipe_through([:browser])

    live("/", Live.Home, :index, as: :page_frontend)
    live("/categories", Live.Category.Tree, :index, as: :category_frontend)
    live("/categories/stats", Live.Category.StatsTree, :stats, as: :category_frontend)
    live("/categories/:id", Live.Category.Show, :show, as: :category_frontend)
    live("/categories/:id/stats", Live.Category.StatsShow, :show_stats, as: :category_frontend)

    live("/categories/:id/latest_episodes", Live.Category.LatestEpisodes, :latest_episodes,
      as: :category_frontend
    )

    get("/categories/:id/categorized", CategoryFrontendController, :categorized)

    get("/podcasts/liked", PodcastFrontendController, :liked)
    get("/podcasts/popular", PodcastFrontendController, :popular)
    live("/podcasts/:id", Live.Podcast.Show, :show, as: :podcast_frontend)
    live("/podcasts", Live.Podcast.Index, :index, as: :podcast_frontend)
    get("/podcasts/:id/feeds", PodcastFrontendController, :feeds)

    get("/qrcode/:code", QRCodeFrontendController, :generate)

    live("/episodes/:id", Live.Episode.Show, :show, as: :episode_frontend)
    live("/episodes", Live.Episode.Index, :index, as: :episode_frontend)

    live("/users/new", Live.User.New, :new, as: :user_frontend)
    live("/users/:id", Live.User.Show, :show, as: :user_frontend)
    resources("/users", UserFrontendController, only: [:index])
    get("/pro_features", PageFrontendController, :pro_features)

    get("/personas/:id/grant_access", PersonaFrontendController, :grant_access)
    live("/personas", Live.Persona.Index, :index, as: :persona_frontend)
    resources("/personas", PersonaFrontendController, only: [:show])

    get("/forgot_password", UserController, :forgot_password)
    post("/request_login_link", UserController, :request_login_link)

    live("/sessions/new", Live.Session.New, :new, as: :session)
    resources("/sessions", SessionController, only: [:create, :delete])
    get("/sessions/login_via_token", SessionController, :login_via_token)
    get("/sessions/login_from_signup", SessionController, :login_from_signup)
    get("/sessions/confirm_email", SessionController, :confirm_email)

    live("/recommendations", Live.Recommendation.Index, :index, as: :recommendation_frontend)

    live("/recommendations/random", Live.Recommendation.Random, :random,
      as: :recommendation_frontend
    )

    get("/vienna-beamers", MaintenanceController, :vienna_beamers)
    get("/2016/:month/:day/:file", MaintenanceController, :blog_2016)
    get("/2017/:month/:day/:file", MaintenanceController, :blog_2017)
    live("/:pid", Live.Persona.Show, :persona, as: :persona_frontend)
  end

  scope "/", PanWeb do
    pipe_through([:browser_minimal_root_layout])

    live("/episodes/:id/player", Live.Episode.Player, :player, as: :episode_frontend)

    live("/podcasts/:id/subscribe_button", Live.Podcast.Subscribe, :subscribe_button,
      as: :podcast_frontend
    )
  end

  scope "/mydata", PanWeb do
    pipe_through([:json_download])

    get("/download", UserJsonDownloadController, :download)
  end

  scope "/pan", PanWeb do
    pipe_through([:browser, :authenticate_user])

    get("/users/payment_info", UserFrontendController, :payment_info)
    post("/users/like_all_subscribed", UserFrontendController, :like_all_subscribed)
    post("/users/follow_all_subscribed", UserFrontendController, :follow_all_subscribed)
    get("/my_podcasts", UserFrontendController, :my_podcasts)
    get("/my_profile", UserFrontendController, :my_profile)
    get("/my_data", UserFrontendController, :my_data)
    delete("/delete_my_account", UserFrontendController, :delete_my_account)

    get("/edit", UserFrontendController, :edit)
    put("/update", UserFrontendController, :update)
    get("/edit_password", UserFrontendController, :edit_password)
    put("/update_password", UserFrontendController, :update_password)
    post("/go_pro", UserFrontendController, :go_pro)

    post("/personas/:id/claim", PersonaFrontendController, :claim)
    get("/personas/:id/warning", PersonaFrontendController, :warning)
    post("/personas/:id/connect", PersonaFrontendController, :connect)
    post("/personas/:id/disconnect", PersonaFrontendController, :disconnect)
    live("/personas/:id/edit", Live.Persona.Edit, :edit, as: :persona_frontend)

    resources("/opmls", OpmlFrontendController, only: [:new, :create, :index, :delete])
    get("/opmls/:id/import", OpmlFrontendController, :import)
    get("/opmls/:id/download", OpmlFrontendController, :download)

lib/pan_web/frontend_controller/search_frontend_controller.ex
defmodule PanWeb.SearchFrontendController do
  use PanWeb, :controller
  require Logger

  def new(conn, %{"search" => %{"term" => term}}) do
    redirect(conn, to: search_frontend_path(conn, :search, "episodes", term))
  end
end

lib/pan_web/frontend_controllers/search_frontend_controller.ex
defmodule PanWeb.SearchFrontendController do
  use Pan.Web, :controller
  require Logger

  def search(conn, %{"index" => index, "page" => page, "term" => term}) do
    page = String.to_integer(page) || 1
    limit = 10
    offset = (page - 1) * limit
    hits = Pan.Search.query(index: index, term: term, limit: limit, offset: offset)

    render(conn, "#{index}.html",
      hits: hits, page: page, offset: offset, term: term, hits_count: hits["hits"] |> length,
      total: hits["total"], size: limit )
  end

  def search(conn, %{"index" => index, "term" => term}) do
    search(conn, %{"page" => "1", "index" => index, "term" => term})
  end

  def new(conn, %{"search" => %{"term" => term}}) do
    search(conn, %{"page" => "1", "index" => "episodes", "term" => term})
  end
end

lib/pan_web/templates/search_frontend/categories.html.eex
<p>Showing <%= @hits_count %> Categories
   (Nr. <%= @offset + 1 %> to <%= @offset + @hits_count %> of <%= @total %>). You might want to search for
   <%= link "podcasts", to: search_frontend_path(@conn, :search, "podcasts", @term, page: 1) %> |
   <%= link "episodes", to: search_frontend_path(@conn, :search, "episodes", @term, page: 1) %> |
   <%= link "personas", to: search_frontend_path(@conn, :search, "personas", @term, page: 1) %>
   instead.
</p>

<div style= "margin-bottom: -30px; margin-top: -20px;">
  <%= pagination_links(@conn, %Scrivener.Page{total_pages: min(100, round(@total / @size + 0.5)), page_number: @page},
                       ["personas", @term], path: &search_frontend_path/5, action: :search) %>
</div>

<%= for hit <- @hits["hits"] do %>
  <hr/>

  <h3 style="margin-bottom: 5px;">
    <%= icon("folder-heroicons-outline") %> Category
    <%= link hit["_source"]["title"], to: category_frontend_path(PanWeb.Endpoint, :show, hit["_id"]) %>
  </h3>
  <p class="small"><%= link category_frontend_url(PanWeb.Endpoint, :show, hit["_id"]),
               to: category_frontend_url(PanWeb.Endpoint, :show, hit["_id"]) %></p>
<% end %>

<hr/>

<p>Showing <%= @hits_count %> Categories
   (Nr. <%= @offset + 1 %> to <%= @offset + @hits_count %> of <%= @total %>). You might want to search for
   <%= link "podcasts", to: search_frontend_path(@conn, :search, "podcasts", @term, page: 1) %> |
   <%= link "episodes", to: search_frontend_path(@conn, :search, "episodes", @term, page: 1) %> |
   <%= link "personas", to: search_frontend_path(@conn, :search, "personas", @term, page: 1) %>
   instead.
</p>

<div style= "margin-top: -20px;">
  <%= pagination_links(@conn, %Scrivener.Page{total_pages: min(100, round(@total / @size + 0.5)), page_number: @page},
                       ["categories", @term], path: &search_frontend_path/5, action: :search) %>

</div>
<p>
  You can mask your search terms with an asterisk at the end or the beginning of the search term,
  as long as there are 3 characters left.<br/>
  So "sciece", "sci*", "*sci" or "*ien*" will work, while "*ce" will not.
</p>

lib/pan_web/templates/search_frontend/done.html.eex
Done.

lib/pan_web/templates/search_frontend/episodes.html.eex
<p>Showing <%= @hits_count %> Episodes
   (Nr. <%= @offset + 1 %> to <%= @offset + @hits_count %> of <%= @total %>). You might want to search for
   <%= link "categories", to: search_frontend_path(@conn, :search, "categories", @term, page: 1) %> |
   <%= link "podcasts", to: search_frontend_path(@conn, :search, "podcasts", @term, page: 1) %> |
   <%= link "personas", to: search_frontend_path(@conn, :search, "personas", @term, page: 1) %>
   instead.
</p>

<div style= "margin-bottom: -30px; margin-top: -20px;">
  <%= pagination_links(@conn, %Scrivener.Page{total_pages: min(100, round(@total / @size + 0.5)), page_number: @page},
                       ["episodes", @term], path: &search_frontend_path/5, action: :search) %>
</div>

<%= for hit <- @hits["hits"] do %>
  <hr/>

  <h3 style="margin-bottom: 5px; margin-top: 0px;">
    <%= icon("headphones-lineawesome-solid") %> Episode &nbsp;
    <%= link hit["_source"]["title"], to: episode_frontend_path(PanWeb.Endpoint, :show, hit["_id"]),
                                          style: "color:#1a0dab" %>
    <%= for language <- hit["_source"]["languages"], do: language["emoji"] <> " " %>
  </h3>

  <p class="small">
    <%= link "https://panoptikum.io" <> episode_frontend_path(PanWeb.Endpoint, :show, hit["_id"]),
          to: episode_frontend_path(PanWeb.Endpoint, :show, hit["_id"]),
          style: "color:#006621" %>
  </p>

  <%= for {highlight_key, highlight_values} <- hit["highlight"] do %>
    <%= if highlight_values != [] do %>
      <%= for highlight_value <- highlight_values do %>
        <p class="small" style="margin-bottom: 1px;">
          <i><%= String.capitalize(highlight_key) %>:</i>
          <%= raw(highlight_value) %>
        </p>
      <% end %>
    <% end %>
  <% end %>

  <p class="small"><i>Episode captured:</i> <%= format_datetime(hit["_source"]["inserted_at"]) %></p>

  <%= for {gig, index} <- Enum.with_index(hit["_source"]["gigs"]) do %>
    <%= if index > 0, do: raw("&nbsp;·&nbsp;") %>

    <%= link [icon("user-astronaut-lineawesome-solid"), " ", gig["persona_name"]],
            to: persona_frontend_path(PanWeb.Endpoint, :show, gig["persona_id"]),
            class: "btn btn-xs btn-lavender" %>
    <span class="label label-success"><%= gig["role"] %></span>
  <% end %>

  <hr style="margin-top: -15px; visibility:hidden;" />

  <%= link [icon("podcast-lineawesome-solid"), " ", truncate_string(hit["_source"]["podcast"]["title"], 50)],
                  to: podcast_frontend_path(PanWeb.Endpoint, :show, hit["_source"]["podcast_id"]),
                  class: "btn btn-default btn-xs",
                  style: "color: #000" %>
<% end %>

<hr/>
<p>Showing <%= @hits_count %> Episodes
   (Nr. <%= @offset + 1 %> to <%= @offset + @hits_count %> of <%= @total %>). You might want to search for
   <%= link "categories", to: search_frontend_path(@conn, :search, "categories", @term, page: 1) %> |
   <%= link "podcasts", to: search_frontend_path(@conn, :search, "podcasts", @term, page: 1) %> |
   <%= link "personas", to: search_frontend_path(@conn, :search, "personas", @term, page: 1) %>
   instead.
</p>
<div style= "margin-top: -20px;">
  <%= pagination_links(@conn, %Scrivener.Page{total_pages: min(100, round(@total / @size + 0.5)), page_number: @page},
                       ["episodes", @term], path: &search_frontend_path/5, action: :search) %>

</div>
<p>
  You can mask your search terms with an asterisk at the end or the beginning of the search term,
  as long as there are 3 characters left.<br/>
  So "sciece", "sci*", "*sci" or "*ien*" will work, while "*ce" will not.
</p>

lib/pan_web/templates/search_frontend/error.html.eex
Uh, an error has happened!<br/>
Sorry for that, we have been informed about it and will fix asap.

lib/pan_web/templates/search_frontend/personas.html.eex
<p>Showing <%= @hits_count %> Personas
   (Nr. <%= @offset + 1 %> to <%= @offset + @hits_count %> of <%= @total %>). You might want to search for
   <%= link "categories", to: search_frontend_path(@conn, :search, "categories", @term, page: 1) %> |
   <%= link "podcasts", to: search_frontend_path(@conn, :search, "podcasts", @term, page: 1) %> |
   <%= link "episodes", to: search_frontend_path(@conn, :search, "episodes", @term, page: 1) %>
   instead.
</p>

<div style= "margin-bottom: -30px; margin-top: -20px;">
  <%= pagination_links(@conn, %Scrivener.Page{total_pages: min(100, round(@total / @size + 0.5)), page_number: @page},
                       ["personas", @term], path: &search_frontend_path/5, action: :search) %>
</div>

<%= for hit <- @hits["hits"] do %>
  <div class="row">
    <hr/>
    <div class="col-md-2">
      <%= if String.length(hit["_source"]["thumbnail_url"]) > 0 do %>
        <%= img_tag("https://panoptikum.io/" <> hit["_source"]["thumbnail_url"],
                    height: 120,
                    alt: hit["image_title"],
                    class: "thumbnail",
                    id: "photo",
                    style: "margin-bottom:0px;") %>
      <% else %>
        <img src="/images/missing-persona.png" alt="missing image" height="120"
            class="thumbnail" syle="margin-bottom:0px;" />
      <% end %>
    </div>

    <div class="col-md-10">
      <h3 style="margin-bottom: 5px; margin-top: 5px;">
        <%= icon("user-heroicons-outline") %> Persona
        <%= link truncate_string(hit["_source"]["name"], 75), to: persona_frontend_path(PanWeb.Endpoint, :show, hit["_id"]) %>
      </h3>
      <p class="small"><%= link persona_frontend_url(PanWeb.Endpoint, :show, hit["_id"]),
                  to: persona_frontend_url(PanWeb.Endpoint, :show, hit["_id"]) %></p>

      <%= for {highlight_key, highlight_values} <- hit["highlight"] do %>
        <%= if highlight_values != [] do %>
          <%= for highlight_value <- highlight_values do %>
            <p class="small" style="margin-bottom: 1px;">
              <i><%= String.capitalize(highlight_key) %>:</i>
              <%= raw(highlight_value) %>
            </p>
          <% end %>
        <% end %>
      <% end %>

      <%= for {engagement, index} <- Enum.with_index(hit["_source"]["engagements"]) do %>
        <%= if index > 0, do: raw("&nbsp;·&nbsp;") %>
        <%= link [icon("podcast-lineawesome-solid"), " ", truncate_string(engagement["podcast_title"], 50)],
                 to: podcast_frontend_path(PanWeb.Endpoint, :show, engagement["podcast_id"]),
                 class: "btn btn-default btn-xs",
                style: "color: #000" %>
        <span class="label label-success"><%= engagement["role"] %></span>
      <% end %>
    </div>
  </div>
<% end %>

<hr/>
<p>Showing <%= @hits_count %> Personas
   (Nr. <%= @offset + 1 %> to <%= @offset + @hits_count %> of <%= @total %>). You might want to search for
   <%= link "categories", to: search_frontend_path(@conn, :search, "categories", @term, page: 1) %> |
   <%= link "podcasts", to: search_frontend_path(@conn, :search, "podcasts", @term, page: 1) %> |
   <%= link "episodes", to: search_frontend_path(@conn, :search, "episodes", @term, page: 1) %>
   instead.
</p>

<div style="margin-top: -20px;">
  <%= pagination_links(@conn, %Scrivener.Page{total_pages: min(100, round(@total / @size + 0.5)), page_number: @page},
                       ["personas", @term], path: &search_frontend_path/5, action: :search) %>
</div>
<p>
  You can mask your search terms with an asterisk at the end or the beginning of the search term,
  as long as there are 3 characters left.<br/>
  So "sciece", "sci*", "*sci" or "*ien*" will work, while "*ce" will not.
</p>

lib/pan_web/templates/search_frontend/podcasts.html.eex
<p>Showing <%= @hits_count %> Podcasts
   (Nr. <%= @offset + 1 %> to <%= @offset + @hits_count %> of <%= @total %>). You might want to search for
   <%= link "categories", to: search_frontend_path(@conn, :search, "categories", @term, page: 1) %> |
   <%= link "episodes", to: search_frontend_path(@conn, :search, "episodes", @term, page: 1) %> |
   <%= link "personas", to: search_frontend_path(@conn, :search, "personas", @term, page: 1) %>
   instead.
</p>

<div style= "margin-bottom: -30px; margin-top: -20px;">
  <%= pagination_links(@conn, %Scrivener.Page{total_pages: min(100, round(@total / @size + 0.5)), page_number: @page},
                       ["podcasts", @term], path: &search_frontend_path/5, action: :search) %>
</div>

<%= for hit <- @hits["hits"] do %>
  <hr/>
  <div class="row">
    <div class="col-md-2">
      <%= if String.length(hit["_source"]["thumbnail_url"]) > 0 do %>
        <%= img_tag("https://panoptikum.io" <> hit["_source"]["thumbnail_url"],
                    height: 120,
                    alt: hit["_source"]["image_title"],
                    class: "thumbnail",
                    id: "photo",
                    style: "margin-bottom:0px;") %>
      <% else %>
        <img src="/images/missing-podcast.png" alt="missing image" height="120"
            class="thumbnail" syle="margin-bottom:0px;" />
      <% end %>
    </div>

    <div class="col-md-10">
      <h3 style="margin-bottom: 5px; margin-top: 0px;">
        <%= icon("podcast-lineawesome-solid") %>
        Podcast &nbsp;
        <%= link hit["_source"]["title"], to: podcast_frontend_path(PanWeb.Endpoint, :show, hit["_id"]),
                                          style: "color:#1a0dab" %>
        <%= for language <- hit["_source"]["languages"], do: language["emoji"] %>
      </h3>

      <p class="small">
        <%= link "https://panoptikum.io" <> podcast_frontend_path(PanWeb.Endpoint, :show, hit["_id"]),
              to: podcast_frontend_path(PanWeb.Endpoint, :show, hit["_id"]),
              style: "color:#006621" %><br/>
      </p>

      <%= for {highlight_key, highlight_values} <- hit["highlight"] do %>
        <%= if highlight_values != [] do %>
          <%= for highlight_value <- highlight_values do %>
            <p class="small" style="margin-bottom: 1px;">
              <i><%= String.capitalize(highlight_key) %>:</i>
              <%= raw(highlight_value) %>
            </p>
          <% end %>
        <% end %>
      <% end %>

      <p style="line-height: 175%;">
        <%= for {engagement, index} <- Enum.with_index(hit["_source"]["engagements"]) do %>
          <%= if index > 0, do: raw("&nbsp;·&nbsp;") %>

          <%= link [icon("user-astronaut-lineawesome-solid"), " ", truncate_string(engagement["persona_name"], 75)],
                  to: persona_frontend_path(PanWeb.Endpoint, :show, engagement["persona_id"]),
                  class: "btn btn-xs btn-lavender" %>
          <span class="label label-success"><%= engagement["role"] %></span>
        <% end %>
      </p>

      <hr style="margin-top: -15px; visibility:hidden;" />

      <%= for {category, index} <- Enum.with_index(hit["_source"]["categories"]) do %>
        <%= if index > 0, do: raw("&nbsp;·&nbsp;") %>
        <%= link [icon("folder-heroicons-outline"), " ", category["title"]],
                to: category_frontend_path(PanWeb.Endpoint, :show, category["id"]),
                class: "btn btn-xs btn-light-gray" %>
      <% end %>
    </div>
  </div>
<% end %>

<hr/>

<p>Showing <%= @hits_count %> Podcasts
   (Nr. <%= @offset + 1 %> to <%= @offset + @hits_count %> of <%= @total %>). You might want to search for
   <%= link "categories", to: search_frontend_path(@conn, :search, "categories", @term, page: 1) %> |
   <%= link "episodes", to: search_frontend_path(@conn, :search, "episodes", @term, page: 1) %> |
   <%= link "personas", to: search_frontend_path(@conn, :search, "personas", @term, page: 1) %>
   instead.
</p>

<div style= "margin-top: -20px;">
  <%= pagination_links(@conn, %Scrivener.Page{total_pages: min(100, round(@total / @size + 0.5)), page_number: @page},
                       ["podcasts", @term], path: &search_frontend_path/5, action: :search) %>
</div>

<p>
  You can mask your search terms with an asterisk at the end or the beginning of the search term,
  as long as there are 3 characters left.<br/>
  So "sciece", "sci*", "*sci" or "*ien*" will work, while "*ce" will not.
</p>