lib/pan_web/router.ex
defmodule PanWeb.Router do
  use PanWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {PanWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PanWeb.Auth, repo: Pan.Repo)
  end

  pipeline :browser_minimal_root_layout do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {PanWeb.LayoutView, :minimal_root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PanWeb.Auth, repo: Pan.Repo)
  end

  pipeline :json_api do
    plug(:accepts, ["json-api"])
    plug(:fetch_session)
    plug(:put_secure_browser_headers)
    plug(PanWeb.Api.Auth, repo: Pan.Repo)
  end

  pipeline :json_download do
    plug(:accepts, ["json-api"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PanWeb.Auth, repo: Pan.Repo)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :bot do
    plug(:accepts, ["json"])
  end

  pipeline :admin_layout do
    plug(:put_layout, html: {PanWeb.LayoutView, :admin})
  end

  scope "/jsonapi", PanWeb.Api, as: :api do
    pipe_through(:json_api)

    resources("/alternate_feeds", AlternateFeedController, only: [:show])
    resources("/chapters", ChapterController, only: [:show])

    get("/categories/search", CategoryController, :search)
    resources("/categories", CategoryController, only: [:show])

    resources("/enclosures", EnclosureController, only: [:show])
    resources("/engagements", EngagementController, only: [:show])

    get("/episodes/search", EpisodeController, :search)
    resources("/episodes", EpisodeController, only: [:index, :show])

    resources("/feeds", FeedController, only: [:show])
    resources("/gigs", GigController, only: [:show])
    resources("/languages", LanguageController, only: [:index, :show])

    get("/personas/search", PersonaController, :search)
    resources("/personas", PersonaController, only: [:index, :show])

    resources("/users", UserController, only: [:index, :show, :create])

    get("/recommendations/random", RecommendationController, :random)
    resources("/recommendations", RecommendationController, only: [:index, :show])

    get("/podcasts/search", PodcastController, :search)
    get("/podcasts/most_subscribed", PodcastController, :most_subscribed)
    get("/podcasts/most_liked", PodcastController, :most_liked)
    get("/podcasts/last_updated", PodcastController, :last_updated)
    resources("/podcasts", PodcastController, only: [:index, :show])

    resources("/likes", LikeController, only: [:show])
    resources("/follows", FollowController, only: [:show])
    resources("/subscriptions", SubscriptionController, only: [:show])

    post("/login", SessionController, :login)
    post("/get_token", SessionController, :login)
  end

  scope "/jsonapi/pan", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_user])

    post("/likes/toggle", LikeController, :toggle)
    post("/follows/toggle", FollowController, :toggle)
    post("/subscriptions/toggle", SubscriptionController, :toggle)
    post("/gigs/toggle", GigController, :toggle)

    resources("/recommendations", RecommendationController, only: [:create])
    get("/recommendations/my", RecommendationController, :my)

    get("/podcasts/:id/trigger_update", PodcastController, :trigger_update)
    get("/podcasts/:id/trigger_episode_update", PodcastController, :trigger_episode_update)

    get("/podcasts/i_follow", PodcastController, :i_follow)
    get("/podcasts/i_like", PodcastController, :i_like)
    get("/podcasts/i_subscribed", PodcastController, :i_subscribed)
    get("/podcasts/also_listened_to", PodcastController, :also_listened_to)
    get("/podcasts/also_liked", PodcastController, :also_liked)

    get("/categories/my", CategoryController, :my)
    post("/like_all_subscribed_podcasts", LikeController, :like_all_subscribed_podcasts)
    post("/follow_all_subscribed_podcasts", FollowController, :follow_all_subscribed_podcasts)

    get("/opmls/:id/import", OpmlController, :import)
    resources("/opmls", OpmlController, only: [:index, :show, :create, :delete])

    resources("/feed_backlogs", FeedBacklogController, only: [:show, :create])

    get("/users/my", UserController, :my)

    patch("/update_password", UserController, :update_password)
    put("/update_password", UserController, :update_password)
    patch("/update_user", UserController, :update_user)
    put("/update_user", UserController, :update_user)

    post("/personas/:id/claim", PersonaController, :claim)
    resources("/personas", PersonaController, only: [:update])

    resources("/delegations", DelegationController, only: [:show])
  end

  scope "/jsonapi/pro", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_pro_user])

    post("/personas/:id/redirect", PersonaController, :redirect)
    post("/personas/:id/cancel_redirect", PersonaController, :cancel_redirect)
    put("/personas/:id", PersonaController, :pro_update)
    patch("/personas/:id", PersonaController, :pro_update)

    post("/delegations/toggle", DelegationController, :toggle)
  end

  scope "/jsonapi/moderator", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_moderator])
    # no moderator specific api routes defined yet
  end

  scope "/bot", PanWeb do
    pipe_through(:bot)

    get("/webhook", BotController, :webhook)
    post("/webhook", BotController, :message)
  end

  scope "/search", PanWeb do
    pipe_through([:browser])

    post("/", SearchFrontendController, :new)
    live("/:index/:term", Live.Search, :search, as: :search_frontend)
  end

  live_session :admin, on_mount: {PanWeb.Live.Auth, :admin} do
    scope "/admin", PanWeb do
      pipe_through([:browser, :authenticate_admin, :admin_layout])
      live("/", Live.Admin.Dashboard, :home, as: :dashboard)
      live("/sandbox", Live.Admin.Sandbox, :home, as: :sandbox)

      live("/databrowser/:resource", Live.Admin.Databrowser.Index, :index, as: :databrowser)

      live("/databrowser/:resource/db_indices", Live.Admin.Databrowser.DbIndex, :db_indices,
        as: :databrowser
      )

      live(
        "/databrowser/:resource/schema_definition",
        Live.Admin.Databrowser.SchemaDefinition,
        :schema_definition,
        as: :databrowser
      )

      live("/databrowser/:resource/new", Live.Admin.Databrowser.New, :new, as: :databrowser)
      live("/databrowser/:resource/:id", Live.Admin.Databrowser.Show, :show, as: :databrowser)

      live("/databrowser/:resource/:id/edit", Live.Admin.Databrowser.Edit, :edit,
        as: :databrowser
      )

      live(
        "/databrowser/:resource/new/:first_column/:first_id/:second_column/:second_id",
        Live.Admin.Databrowser.NewAssociation,
        :new_association,
        as: :databrowser
      )

      live(
        "/databrowser/:owner/:owner_id/has_many/:association",
        Live.Admin.Databrowser.HasMany,
        :has_many,
        as: :databrowser
      )

      live(
        "/databrowser/:owner/:owner_id/many_to_many/:association",
        Live.Admin.Databrowser.ManyToMany,
        :many_to_many,
        as: :databrowser
      )

      live(
        "/databrowser/show_mediating/:resource/:first_column/:first_id/:second_column/:second_id/id",
        Live.Admin.Databrowser.ShowMediating,
        :show_mediating,
        as: :databrowser
      )

      live(
        "/databrowser/edit_mediating/:resource/:first_column/:first_id/:second_column/:second_id/id",
        Live.Admin.Databrowser.EditMediating,
        :edit_mediating,
        as: :databrowser
      )
    end
  end

  scope "/", PanWeb do
    pipe_through([:browser])

    live("/", Live.Home, :index, as: :page_frontend)
    live("/categories", Live.Category.Tree, :index, as: :category_frontend)
    live("/categories/stats", Live.Category.StatsTree, :stats, as: :category_frontend)
    live("/categories/:id", Live.Category.Show, :show, as: :category_frontend)
    live("/categories/:id/stats", Live.Category.StatsShow, :show_stats, as: :category_frontend)

    live("/categories/:id/latest_episodes", Live.Category.LatestEpisodes, :latest_episodes,
      as: :category_frontend
    )

    get("/categories/:id/categorized", CategoryFrontendController, :categorized)

    get("/podcasts/liked", PodcastFrontendController, :liked)
    get("/podcasts/popular", PodcastFrontendController, :popular)
    live("/podcasts/:id", Live.Podcast.Show, :show, as: :podcast_frontend)
    live("/podcasts", Live.Podcast.Index, :index, as: :podcast_frontend)
    get("/podcasts/:id/feeds", PodcastFrontendController, :feeds)

    get("/qrcode/:code", QRCodeFrontendController, :generate)

    live("/episodes/:id", Live.Episode.Show, :show, as: :episode_frontend)
    live("/episodes", Live.Episode.Index, :index, as: :episode_frontend)

    live("/users/new", Live.User.New, :new, as: :user_frontend)
    live("/users/:id", Live.User.Show, :show, as: :user_frontend)
    resources("/users", UserFrontendController, only: [:index])
    get("/pro_features", PageFrontendController, :pro_features)

    get("/personas/:id/grant_access", PersonaFrontendController, :grant_access)
    live("/personas", Live.Persona.Index, :index, as: :persona_frontend)
    resources("/personas", PersonaFrontendController, only: [:show])

    get("/forgot_password", UserController, :forgot_password)
    post("/request_login_link", UserController, :request_login_link)

    live("/sessions/new", Live.Session.New, :new, as: :session)
    resources("/sessions", SessionController, only: [:create, :delete])
    get("/sessions/login_via_token", SessionController, :login_via_token)
    get("/sessions/login_from_signup", SessionController, :login_from_signup)

lib/pan_web/api/views/podcast_view.ex
defmodule PanWeb.Api.PodcastView do
  use PanWeb, :view
  use JaSerializer.PhoenixView

  def type(_, _), do: "podcast"

  location(:location)

  attributes([
    :title,
    :website,
    :description,
    :summary,
    :image_title,
    :orig_image_url,
    :last_build_date,
    :payment_link_title,
    :payment_link_url,
    :explicit,
    :blocked,
    :update_paused,
    :update_intervall,
    :next_update,
    :retired,
    :unique_identifier,
    :episodes_count,
    :followers_count,
    :likes_count,
    :subscriptions_count,
    :latest_episode_publishing_date,
    :publication_frequency,
    :manually_updated_at,
    :full_text,
    :last_error_message,
    :last_error_occured
  ])

  has_many(:episodes, serializer: PanWeb.Api.PlainEpisodeView, include: false)
  has_many(:categories, serializer: PanWeb.Api.PlainCategoryView, include: false)
  has_many(:languages, serializer: PanWeb.Api.LanguageView, include: false)
  has_many(:languages, serializer: PanWeb.Api.LanguageView, include: false)
  has_many(:engagements, serializer: PanWeb.Api.PlainEngagmentView, include: false)
  has_many(:contributors, serializer: PanWeb.Api.PlainPersonaView, include: false)
  has_many(:recommendations, serializer: PanWeb.Api.PodcastRecommendationView, include: false)
  has_many(:feeds, serializer: PanWeb.Api.PlainFeedView, include: false)

  def location(podcast, conn) do
    api_podcast_url(conn, :show, podcast)
  end

  def orig_image_url(podcast, _conn) do
    podcast.image_url
  end
end

defmodule PanWeb.Api.PlainPodcastView do
  use PanWeb, :view
  use JaSerializer.PhoenixView

  def type(_, _), do: "podcast"

  location(:location)

  attributes([
    :title,
    :website,
    :description,
    :image_title,
    :orig_image_url,
    :latest_episode_publishing_date
  ])

  def location(podcast, conn) do
    api_podcast_url(conn, :show, podcast)
  end

  def orig_image_url(podcast, _conn) do
    podcast.image_url
  end
end

lib/pan_web/live/admin/podcast/retirement.ex
defmodule PanWeb.Live.Admin.Podcast.Retirement do
  use Surface.LiveView,
    layout: {PanWeb.LayoutView, :live_admin}

  on_mount {PanWeb.Live.Auth, :admin}
  alias PanWeb.{Podcast, Surface.Admin.IndexGrid}

  def handle_info({:count, id: id, module: module}, socket) do
    send_update(module, id: id, count: :now)
    {:noreply, socket}
  end

  def render(assigns) do
    ~F"""
    <h1 class="text-2xl m-4">Retirement</h1>

    <div class="bg-info-light/50 rounded-lg border border-gray-dark p-2 m-4">
      <p>Select Podcast and use [Edit] to change the retirement flag. Beware: after saving the edited record, you end up in the databrowser, not here!</p>
    </div>

    <IndexGrid id="podcast-indexgrid"
               heading="Listing Pocasts"
               model={Podcast}
               cols={[
                 %{field: :id, label: "Id", searchable: true, sortable: true, type: :id},
                 %{field: :title, label: "Title", type: :string, searchable: true, sortable: true},
                 %{field: :retired, label: "Retired", type: :string, searchable: true, sortable: true},
                 %{field: :last_build_date, label: "Last build date", type: :naive_datetime, searchable: true, sortable: true},
                 %{field: :latest_episode_publishing_date, label: "Latest episode publishing date", type: :naive_datetime, searchable: true, sortable: true}
                     ]}
               buttons={[:show, :edit, :pagination, :number_of_records, :search]} />
    """
  end
end

lib/pan_web/live/admin/podcast/stale.ex
defmodule PanWeb.Live.Admin.Podcast.Stale do
  use Surface.LiveView,
    layout: {PanWeb.LayoutView, :live_admin},
    container: {:div, class: "m-4"}

  on_mount {PanWeb.Live.Auth, :admin}
  alias PanWeb.{Podcast, Endpoint}
  alias PanWeb.Surface.{LinkButton, Admin.SortLink}
  import PanWeb.Router.Helpers

  def mount(_params, _session, socket) do
    Phoenix.PubSub.subscribe(:pan_pubsub, "admin")
    Process.send_after(self(), :refresh, 5 * 1000)
    {:ok, assign(socket, sort_order: :asc, sort_by: :next_update) |> fetch()}
  end

  defp fetch(%{assigns: %{sort_by: sort_by, sort_order: sort_order}} = socket) do
    assign(socket,
      stale_podcasts: Podcast.stale(sort_by, sort_order, 10),
      stale_podcasts_count: Podcast.count_stale()
    )
  end

  def handle_info(:refresh, socket) do
    Process.send_after(self(), :refresh, 60 * 1000)
    {:noreply, socket |> fetch()}
  end

  def handle_info(payload, socket) do
    {:noreply, push_event(socket, "notification", payload)}
  end

  def handle_event("sort", %{"sort-by" => sort_by, "sort-order" => sort_order}, socket) do
    {:noreply,
     assign(socket,
       sort_by: String.to_atom(sort_by),
       sort_order: String.to_atom(sort_order)
     )
     |> fetch()}
  end

  def handle_event("trigger-update", _, socket) do
    Task.start(fn ->
      trigger_update()
    end)

    {:noreply, socket}
  end

  defp trigger_update() do
    Podcast.get_one_stale()
    |> Podcast.import_stale()

    trigger_update()
  end

  def vienna_string(naive_date_time) do
    naive_date_time
    |> DateTime.from_naive!("Etc/UTC")
    |> DateTime.shift_zone!("Europe/Vienna")
    |> Calendar.strftime("%c")
  end

  def render(assigns) do
    ~F"""
      <button id="notification-hook-target"
              phx-hook="Notification"
              :on-click="trigger-update"
              class="border border-gray-darker text-white text-sm rounded bg-info hover:bg-info-light px-2 py-1 float-right">
      Episode import
    </button>

    <h1 class="text-3xl">{@stale_podcasts_count} stale podcasts</h1>

    <p>This view is auto-refreshing every 60 seconds.</p>

    <table cellpadding="4" class="my-4">
      <thead>
        <tr>
          <th class="border border-gray-light">
            <SortLink field={:id} click="sort" {=@sort_order} {=@sort_by}>
              ID
            </SortLink>
          </th>
          <th class="border border-gray-light">
            <SortLink field={:title} click="sort" {=@sort_order} {=@sort_by}>
              Title
            </SortLink>
          </th>
          <th class="border border-gray-light">
          <SortLink field={:updated_at} click="sort" {=@sort_order} {=@sort_by}>
            Updated at 🎡
            </SortLink>
          </th>
          <th class="border border-gray-light">
            <SortLink field={:update_intervall} click="sort" {=@sort_order} {=@sort_by}>
              Update intervall
            </SortLink>
          </th>
          <th class="border border-gray-light">
            <SortLink field={:next_update} click="sort" {=@sort_order} {=@sort_by}>
              Next update 🎡
            </SortLink>
          </th>
          <th class="border border-gray-light">
          <SortLink field={:failure_count} click="sort" {=@sort_order} {=@sort_by}>
            Failure count
          </SortLink>
          </th>
          <th class="border border-gray-light">Feed url</th>
        </tr>
      </thead>
      <tbody>
        {#for podcast <- @stale_podcasts}
          <tr>
            <td class="border border-gray-light text-right">
              <LinkButton title={podcast.id}
                          to={databrowser_path(Endpoint, :show, "podcast", podcast.id)}
                          class="border-gray text-white bg-primary hover:bg-primary-light rounded" /></td>
            <td class="border border-gray-light">{podcast.title}</td>
            <td class="border border-gray-light whitespace-nowrap">{podcast.updated_at |> vienna_string()}</td>
            <td class="border border-gray-light">{podcast.update_intervall}</td>
            <td class="border border-gray-light whitespace-nowrap">{podcast.next_update |> vienna_string()}</td>
            <td class="border border-gray-light">{podcast.failure_count}</td>
            <td class="border border-gray-light">{podcast.feed_url}</td>
          </tr>
        {/for}
      </tbody>
    </table>
    """
  end
end

lib/pan_web/templates/podcast/_podcast.html.eex
<h2>Show podcast</h2>

<dl class="dl-horizontal">

  <dt>Title</dt>
  <dd><%= @podcast.title %></dd>

  <dt>Website</dt>
  <dd><%= @podcast.website %></dd>

  <dt>Description</dt>
  <dd><%= @podcast.description %></dd>

  <dt>Summary</dt>
  <dd><%= @podcast.summary %></dd>

  <dt>Image title</dt>
  <dd><%= @podcast.image_title %></dd>

  <dt>Image url</dt>
  <dd><%= @podcast.image_url %></dd>

  <dt>Last build date</dt>
  <dd><%= @podcast.last_build_date && Timex.format!(@podcast.last_build_date, "{ISOdate} {h24}:{m}:{s}") %></dd>

  <dt>Updated at</dt>
  <dd><%= @podcast.updated_at && Timex.format!(@podcast.updated_at, "{ISOdate} {h24}:{m}:{s}") %></dd>

  <dt>Update intervall</dt>
  <dd><%= @podcast.update_intervall %></dd>

  <dt>Next update</dt>
  <dd><%= @podcast.next_update && Timex.format!(@podcast.next_update, "{ISOdate} {h24}:{m}:{s}") %></dd>

  <dt>Inserted at</dt>
  <dd><%= @podcast.inserted_at && Timex.format!(@podcast.inserted_at, "{ISOdate} {h24}:{m}:{s}") %></dd>

  <dt>Payment link title</dt>
  <dd><%= @podcast.payment_link_title %></dd>

  <dt>Payment link url</dt>
  <dd><%= @podcast.payment_link_url %></dd>

  <dt>Blocked</dt>
  <dd><%= @podcast.blocked %></dd>

  <dt>Contributors</dt>
  <%= for owner <- @podcast.contributors do %>
    <dd><%= owner.name %></dd>
  <% end %>

  <dt>Explicit</dt>
  <dd><%= @podcast.explicit %></dd>

  <dt>Unique identifier</dt>
  <dd><%= @podcast.unique_identifier %></dd>

  <dt>Update paused</dt>
  <dd><%= @podcast.update_paused %></dd>

  <dt>Failure count</dt>
  <dd><%= @podcast.failure_count %></dd>

  <dt>Retired</dt>
  <dd><%= @podcast.retired %></dd>

  <dt>Episodes count</dt>
  <dd><%= @podcast.episodes_count %></dd>

  <dt>Followers count</dt>
  <dd><%= @podcast.followers_count %></dd>

  <dt>Likes_count</dt>
  <dd><%= @podcast.likes_count %></dd>

  <dt>Subscriptions_count</dt>
  <dd><%= @podcast.subscriptions_count %></dd>

  <dt>Latest episode publishing date</dt>
  <dd><%= @podcast.latest_episode_publishing_date && Timex.format!(@podcast.latest_episode_publishing_date, "{ISOdate} {h24}:{m}:{s}") %></dd>

  <dt>Publication frequency</dt>
  <dd><%= if @podcast.publication_frequency, do: Float.round(@podcast.publication_frequency, 2) %> days</dd>

  <dt>Manually updated at</dt>
  <dd><%= @podcast.manually_updated_at && Timex.format!(@podcast.manually_updated_at, "{ISOdate} {h24}:{m}:{s}") %></dd>

  <dt>Indexed by Full Text Indexed</dt>
  <dd><%= @podcast.full_text %></dd>

  <dt>Thumbnail created</dt>
  <dd><%= @podcast.thumbnailed %></dd>

  <dt>Last error message</dt>
  <dd><%= @podcast.last_error_message %></dd>

  <dt>Last error occured</dt>
  <dd><%= @podcast.last_error_occured && Timex.format!(@podcast.last_error_occured, "{ISOdate} {h24}:{m}:{s}") %></dd>
</dl>

<%= link "Show", to: podcast_path(@conn, :show, @podcast) %>

lib/pan_web/templates/podcast/duplicates.html.heex
<div class="m-4">
  <h1 class="text-3xl">
    Duplicate Feeds
  </h1>

  <ul class="list-disc ml-4">
    <%= for feed <- @feeds do %>
      <li class="flex space-x-4">
        <div>
          <%= feed.self_link_url %>
        </div>
        <div>
          Podcast: <%= link(feed.podcast.title,
            to: databrowser_path(@conn, :show, "podcast", feed.podcast),
            class: "text-link hover:text-link-dark"
          ) %>
        </div>
        <%= link("Delete",
          to: podcast_path(@conn, :delete, feed.podcast),
          method: :delete,
          data: [confirm: "Are you sure?"],
          class:
            "border border-gray-dark bg-danger hover:bg-danger-light text-white text-sm py-1 px-2 rounded"
        ) %>
      </li>
    <% end %>
  </ul>
</div>

lib/pan_web/templates/podcast/factory.html.eex
<h2>Listing <%= length(@podcasts) %> podcasts</h2>
<p class="text-right">
...
</p>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>updated_at</th>
      <th>Last build date</th>
      <th>Update Paused</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for podcast <- @podcasts do %>
      <tr>
        <td><%= podcast.id %></td>
        <td><%= podcast.title %></td>
        <td><%= podcast.updated_at %></td>
        <td><%= podcast.last_build_date %></td>
        <td><%= podcast.update_paused %></td>

        <td class="text-right">
          <%= link "Show", to: podcast_path(@conn, :show, podcast),
                           class: "btn btn-default btn-xs" %>
          <%= link "Edit", to: podcast_path(@conn, :edit, podcast),
                           class: "btn btn-default btn-xs" %>
          <%= link "Delete", to: podcast_path(@conn, :delete, podcast),
                             method: :delete,
                             data: [confirm: "Are you sure?"],
                             class: "btn btn-danger btn-xs" %>
          <br/>
          <%= link "Touch", to: podcast_path(@conn, :touch, podcast),
                            class: "btn btn-normal btn-xs" %>
          <%= link "Delta import", to: podcast_path(@conn, :delta_import, podcast),
                                   class: "btn btn-info btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link "New podcast", to: podcast_path(@conn, :new) %>

lib/pan_web/templates/podcast/retirement.html.eex
<h2>Candidates for Retirement</h2>

<table id="candidates" class="table table-striped table-condensed table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Author</th>
      <th>Last build date</th>
      <th>latest Episode: publishing_date</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for podcast <- @candidates do %>
      <tr>
        <td><%= podcast.id %></td>
        <td><%= podcast.title %></td>
        <td><%= PanWeb.PodcastFrontendView.author_button(@conn, podcast) %></td>
        <td><%= podcast.last_build_date %></td>
        <td><%= podcast.last_episode_date %></td>

        <td>
          <nobr>
            <%= link "Show", to: podcast_path(@conn, :show, podcast.id),
                             class: "btn btn-default btn-xs" %>
            <%= link "Edit", to: podcast_path(@conn, :edit, podcast.id),
                             class: "btn btn-warning btn-xs" %>
            <%= link "Retire", to: podcast_path(@conn, :retire, podcast.id),
                             class: "btn btn-info btn-xs" %>
          </nobr>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr/>

<h2>Retired Podcasts</h2>

<table id="retired" class="table table-striped table-condensed table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Author</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for podcast <- @retired do %>
      <tr>
        <td><%= podcast.id %></td>
        <td><%= podcast.title %></td>
        <td><%= PanWeb.PodcastFrontendView.author_button(@conn, podcast) %></td>

        <td>
          <nobr>
            <%= link "Show", to: podcast_path(@conn, :show, podcast.id),
                             class: "btn btn-default btn-xs" %>
            <%= link "Edit", to: podcast_path(@conn, :edit, podcast.id),
                             class: "btn btn-warning btn-xs" %>
          </nobr>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  $(function() {
    $('#candidates').DataTable({aaSorting: []});
    $('#retired').DataTable();
  });
</script>

lib/pan_web/templates/podcast/show.html.eex
<p class="text-right">
  <%= link "Index", to: podcast_path(@conn, :index),
                    class: "btn btn-primary" %>
  <%= link "Factory", to: podcast_path(@conn, :factory), class: "btn btn-primary" %>
  <%= link "Orphans", to: podcast_path(@conn, :orphans), class: "btn btn-primary" %>
  <%= link "Retirement", to: podcast_path(@conn, :retirement), class: "btn btn-primary" %>

</p>

<div class="pull-right">
  <%= link "Edit", to: podcast_path(@conn, :edit, @podcast), class: "btn btn-warning" %>
  <%= link "Delete", to: podcast_path(@conn, :delete, @podcast),
                     method: :delete,
                     data: [confirm: "Are you sure?"],
                     class: "btn btn-danger" %>
  <%= link "Pause", to: podcast_path(@conn, :pause, @podcast), class: "btn btn-info" %>
  <%= link "Delta import", to: podcast_path(@conn, :delta_import, @podcast), class: "btn btn-success" %>
  <%= link "Forced delta import", to: podcast_path(@conn, :forced_delta_import, @podcast), class: "btn btn-success" %>
  <%= link "Contributor import", to: podcast_path(@conn, :contributor_import, @podcast), class: "btn btn-success" %>
  <%= link "Update from feed", to: podcast_path(@conn, :update_from_feed, @podcast), class: "btn btn-success" %>
</div>

<%= render "_podcast.html", podcast: @podcast, conn: @conn %>
<hr/>
<%= render PanWeb.FeedView, "index_table.html", feeds: @podcast.feeds, conn: @conn %>

<h2>Episodes</h2>

<%= render PanWeb.EpisodeView, "_episodes.html", episodes: @podcast.episodes, conn: @conn %>