lib/pan_web/router.ex
defmodule PanWeb.Router do
  use PanWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {PanWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PanWeb.Auth, repo: Pan.Repo)
  end

  pipeline :browser_minimal_root_layout do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {PanWeb.LayoutView, :minimal_root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PanWeb.Auth, repo: Pan.Repo)
  end

  pipeline :json_api do
    plug(:accepts, ["json-api"])
    plug(:fetch_session)
    plug(:put_secure_browser_headers)
    plug(PanWeb.Api.Auth, repo: Pan.Repo)
  end

  pipeline :json_download do
    plug(:accepts, ["json-api"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PanWeb.Auth, repo: Pan.Repo)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :bot do
    plug(:accepts, ["json"])
  end

  pipeline :admin_layout do
    plug(:put_layout, html: {PanWeb.LayoutView, :admin})
  end

  scope "/jsonapi", PanWeb.Api, as: :api do
    pipe_through(:json_api)

    resources("/alternate_feeds", AlternateFeedController, only: [:show])
    resources("/chapters", ChapterController, only: [:show])

    get("/categories/search", CategoryController, :search)
    resources("/categories", CategoryController, only: [:show])

    resources("/enclosures", EnclosureController, only: [:show])
    resources("/engagements", EngagementController, only: [:show])

    get("/episodes/search", EpisodeController, :search)
    resources("/episodes", EpisodeController, only: [:index, :show])

    resources("/feeds", FeedController, only: [:show])
    resources("/gigs", GigController, only: [:show])
    resources("/languages", LanguageController, only: [:index, :show])

    get("/personas/search", PersonaController, :search)
    resources("/personas", PersonaController, only: [:index, :show])

    resources("/users", UserController, only: [:index, :show, :create])

    get("/recommendations/random", RecommendationController, :random)
    resources("/recommendations", RecommendationController, only: [:index, :show])

    get("/podcasts/search", PodcastController, :search)
    get("/podcasts/most_subscribed", PodcastController, :most_subscribed)
    get("/podcasts/most_liked", PodcastController, :most_liked)
    get("/podcasts/last_updated", PodcastController, :last_updated)
    resources("/podcasts", PodcastController, only: [:index, :show])

    resources("/likes", LikeController, only: [:show])
    resources("/follows", FollowController, only: [:show])
    resources("/subscriptions", SubscriptionController, only: [:show])

    post("/login", SessionController, :login)
    post("/get_token", SessionController, :login)
  end

  scope "/jsonapi/pan", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_user])

    post("/likes/toggle", LikeController, :toggle)
    post("/follows/toggle", FollowController, :toggle)
    post("/subscriptions/toggle", SubscriptionController, :toggle)
    post("/gigs/toggle", GigController, :toggle)

    resources("/recommendations", RecommendationController, only: [:create])
    get("/recommendations/my", RecommendationController, :my)

    get("/podcasts/:id/trigger_update", PodcastController, :trigger_update)
    get("/podcasts/:id/trigger_episode_update", PodcastController, :trigger_episode_update)

    get("/podcasts/i_follow", PodcastController, :i_follow)
    get("/podcasts/i_like", PodcastController, :i_like)
    get("/podcasts/i_subscribed", PodcastController, :i_subscribed)
    get("/podcasts/also_listened_to", PodcastController, :also_listened_to)
    get("/podcasts/also_liked", PodcastController, :also_liked)

    get("/categories/my", CategoryController, :my)
    post("/like_all_subscribed_podcasts", LikeController, :like_all_subscribed_podcasts)
    post("/follow_all_subscribed_podcasts", FollowController, :follow_all_subscribed_podcasts)

    get("/opmls/:id/import", OpmlController, :import)
    resources("/opmls", OpmlController, only: [:index, :show, :create, :delete])

    resources("/feed_backlogs", FeedBacklogController, only: [:show, :create])

    get("/users/my", UserController, :my)

    patch("/update_password", UserController, :update_password)
    put("/update_password", UserController, :update_password)
    patch("/update_user", UserController, :update_user)
    put("/update_user", UserController, :update_user)

    post("/personas/:id/claim", PersonaController, :claim)
    resources("/personas", PersonaController, only: [:update])

    resources("/delegations", DelegationController, only: [:show])
  end

  scope "/jsonapi/pro", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_pro_user])

    post("/personas/:id/redirect", PersonaController, :redirect)
    post("/personas/:id/cancel_redirect", PersonaController, :cancel_redirect)
    put("/personas/:id", PersonaController, :pro_update)
    patch("/personas/:id", PersonaController, :pro_update)

    post("/delegations/toggle", DelegationController, :toggle)
  end

  scope "/jsonapi/moderator", PanWeb.Api, as: :api do
    pipe_through([:json_api, :authenticate_api_moderator])
    # no moderator specific api routes defined yet
  end

  scope "/bot", PanWeb do
    pipe_through(:bot)

    get("/webhook", BotController, :webhook)
    post("/webhook", BotController, :message)
  end

  scope "/search", PanWeb do
    pipe_through([:browser])

    post("/", SearchFrontendController, :new)
    live("/:index/:term", Live.Search, :search, as: :search_frontend)
  end

  live_session :admin, on_mount: {PanWeb.Live.Auth, :admin} do
    scope "/admin", PanWeb do
      pipe_through([:browser, :authenticate_admin, :admin_layout])
      live("/", Live.Admin.Dashboard, :home, as: :dashboard)
      live("/sandbox", Live.Admin.Sandbox, :home, as: :sandbox)

      live("/databrowser/:resource", Live.Admin.Databrowser.Index, :index, as: :databrowser)

      live("/databrowser/:resource/db_indices", Live.Admin.Databrowser.DbIndex, :db_indices,
        as: :databrowser
      )

      live(
        "/databrowser/:resource/schema_definition",
        Live.Admin.Databrowser.SchemaDefinition,
        :schema_definition,
        as: :databrowser
      )

      live("/databrowser/:resource/new", Live.Admin.Databrowser.New, :new, as: :databrowser)
      live("/databrowser/:resource/:id", Live.Admin.Databrowser.Show, :show, as: :databrowser)

      live("/databrowser/:resource/:id/edit", Live.Admin.Databrowser.Edit, :edit,
        as: :databrowser
      )

      live(
        "/databrowser/:resource/new/:first_column/:first_id/:second_column/:second_id",
        Live.Admin.Databrowser.NewAssociation,
        :new_association,
        as: :databrowser
      )

      live(
        "/databrowser/:owner/:owner_id/has_many/:association",
        Live.Admin.Databrowser.HasMany,
        :has_many,
        as: :databrowser
      )

      live(
        "/databrowser/:owner/:owner_id/many_to_many/:association",
        Live.Admin.Databrowser.ManyToMany,
        :many_to_many,
        as: :databrowser
      )

      live(
        "/databrowser/show_mediating/:resource/:first_column/:first_id/:second_column/:second_id/id",
        Live.Admin.Databrowser.ShowMediating,
        :show_mediating,
        as: :databrowser
      )

      live(
        "/databrowser/edit_mediating/:resource/:first_column/:first_id/:second_column/:second_id/id",
        Live.Admin.Databrowser.EditMediating,
        :edit_mediating,
        as: :databrowser
      )
    end
  end

  scope "/", PanWeb do
    pipe_through([:browser])

    live("/", Live.Home, :index, as: :page_frontend)
    live("/categories", Live.Category.Tree, :index, as: :category_frontend)
    live("/categories/stats", Live.Category.StatsTree, :stats, as: :category_frontend)
    live("/categories/:id", Live.Category.Show, :show, as: :category_frontend)
    live("/categories/:id/stats", Live.Category.StatsShow, :show_stats, as: :category_frontend)

    live("/categories/:id/latest_episodes", Live.Category.LatestEpisodes, :latest_episodes,
      as: :category_frontend
    )

    get("/categories/:id/categorized", CategoryFrontendController, :categorized)

    get("/podcasts/liked", PodcastFrontendController, :liked)
    get("/podcasts/popular", PodcastFrontendController, :popular)
    live("/podcasts/:id", Live.Podcast.Show, :show, as: :podcast_frontend)
    live("/podcasts", Live.Podcast.Index, :index, as: :podcast_frontend)
    get("/podcasts/:id/feeds", PodcastFrontendController, :feeds)

    get("/qrcode/:code", QRCodeFrontendController, :generate)

    live("/episodes/:id", Live.Episode.Show, :show, as: :episode_frontend)
    live("/episodes", Live.Episode.Index, :index, as: :episode_frontend)

    live("/users/new", Live.User.New, :new, as: :user_frontend)
    live("/users/:id", Live.User.Show, :show, as: :user_frontend)
    resources("/users", UserFrontendController, only: [:index])
    get("/pro_features", PageFrontendController, :pro_features)

    get("/personas/:id/grant_access", PersonaFrontendController, :grant_access)
    live("/personas", Live.Persona.Index, :index, as: :persona_frontend)
    resources("/personas", PersonaFrontendController, only: [:show])

    get("/forgot_password", UserController, :forgot_password)
    post("/request_login_link", UserController, :request_login_link)

    live("/sessions/new", Live.Session.New, :new, as: :session)
    resources("/sessions", SessionController, only: [:create, :delete])
    get("/sessions/login_via_token", SessionController, :login_via_token)
    get("/sessions/login_from_signup", SessionController, :login_from_signup)

lib/pan_web/api/controllers/category_controller.ex
defmodule PanWeb.Api.CategoryController do
  use PanWeb, :controller
  use JaSerializer
  alias PanWeb.{Api.Helpers, Category, CategoryPodcast, Podcast, Subscription}

  def action(conn, _) do
    apply(__MODULE__, action_name(conn), [conn, conn.params, conn.assigns.current_user])
  end

  def index(conn, _params, _user) do
    categories =
      from(c in Category,
        order_by: :title,
        where: is_nil(c.parent_id)
      )
      |> Repo.all()
      |> Repo.preload(children: from(cat in Category, order_by: cat.title))
      |> Repo.preload(:parent)

    render(conn, "index.json-api", data: categories, opts: [include: "children"])
  end

  def show(conn, %{"id" => id} = params, _user) do
    page =
      if is_map(params["page"]) do
        get_in(params, ["page", "number"]) || "1"
      else
        "1"
      end
      |> String.to_integer()

    size =
      if is_map(params["page"]) do
        get_in(params, ["page", "size"]) || "10"
      else
        "10"
      end
      |> String.to_integer()
      |> min(1000)

    offset = (page - 1) * size

    total =
      from(c in PanWeb.CategoryPodcast, where: c.category_id == ^id)
      |> Repo.aggregate(:count, :category_id)

    total_pages = div(total - 1, size) + 1

    links =
      conn
      |> api_category_url(:show, id)
      |> Helpers.pagination_links({page, size, total_pages}, conn)

    category =
      Repo.get(Category, id)
      |> Repo.preload([:children, :parent])
      |> Repo.preload(
        podcasts:
          from(p in Podcast,
            offset: ^offset,
            order_by: [fragment("? DESC NULLS LAST", p.latest_episode_publishing_date)],
            limit: ^size
          )
      )

    if category do
      render(conn, "show.json-api", data: category, opts: [page: links, include: "podcasts"])
    else
      Helpers.send_404(conn)
    end
  end

  def search(conn, params, _user) do
    hits = Pan.Search.query(index: "categories", term: params["filter"], limit: 1000, offset: 0)

    if hits["total"] > 0 do
      category_ids = Enum.map(hits["hits"], fn hit -> String.to_integer(hit["_id"]) end)

      categories =
        from(c in Category, where: c.id in ^category_ids)
        |> Repo.all()
        |> Repo.preload(children: from(cat in Category, order_by: cat.title))
        |> Repo.preload(:parent)

      render(conn, "index.json-api", data: categories, opts: [include: "children"])
    else
      Helpers.send_error(
        conn,
        404,
        "Nothing found",
        "No matching categories found in the data base."
      )
    end
  end

  def my(conn, _params, user) do
    podcasts_subscribed_ids =
      from(s in Subscription,
        where: s.user_id == ^user.id,
        select: s.podcast_id
      )
      |> Repo.all()

    category_ids =
      from(r in CategoryPodcast,
        join: c in assoc(r, :category),
        where: r.podcast_id in ^podcasts_subscribed_ids,
        group_by: c.id,
        select: c.id,
        order_by: [desc: count(r.category_id)],
        limit: 10
      )
      |> Repo.all()

    categories =
      from(c in Category,
        where: c.id in ^category_ids,
        preload: [:children, :parent]
      )
      |> Repo.all()

    render(conn, "index.json-api", data: categories, opts: [include: "children"])
  end
end

lib/pan_web/api/views/category_view.ex
defmodule PanWeb.Api.CategoryView do
  use PanWeb, :view
  use JaSerializer.PhoenixView

  def type(_, _), do: "category"

  location(:location)
  attributes([:title])

  has_one(:parent, serializer: PanWeb.Api.PlainCategoryView, include: false)
  has_many(:children, serializer: PanWeb.Api.PlainCategoryView, include: false)

  has_many(:podcasts, serializer: PanWeb.Api.PlainPodcastView, include: false)

  def location(category, conn) do
    api_category_url(conn, :show, category)
  end
end

defmodule PanWeb.Api.PlainCategoryView do
  use PanWeb, :view
  use JaSerializer.PhoenixView

  def type(_, _), do: "category"

  location(:location)
  attributes([:title])

  def location(category, conn) do
    api_category_url(conn, :show, category)
  end
end

lib/pan_web/live/admin/category/merge.ex
defmodule PanWeb.Live.Admin.Category.Merge do
  use Surface.LiveView, layout: {PanWeb.LayoutView, :live_admin}
  on_mount {PanWeb.Live.Auth, :admin}
  alias PanWeb.Category
  alias PanWeb.Surface.{Icon, Tree, EventButton}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, categories: Category.tree(), from_id: nil, into_id: nil)}
  end

  def handle_event("merge", _, %{assigns: assigns} = socket) do
    Category.merge(assigns.from_id, assigns.into_id)
    {:noreply, assign(socket, categories: Category.tree(), from_id: nil, into_id: nil)}
  end

  def handle_event("selectFrom", %{"node-id" => from_id}, socket) do
    {:noreply, assign(socket, from_id: from_id |> String.to_integer())}
  end

  def handle_event("selectInto", %{"node-id" => into_id}, socket) do
    {:noreply, assign(socket, into_id: into_id |> String.to_integer())}
  end

  def render(assigns) do
    ~F"""
    <h1 class="text-3xl m-4">Merging categories</h1>

    <div class="flex m-4 space-x-4">
      <Tree id="fromTree"
            nodes={@categories}
            select="selectFrom"
            selected_id={@from_id}/>
      <Tree id="intoTree"
            nodes={@categories}
            select="selectInto"
            selected_id={@into_id} />

      <div>
        <EventButton event="merge">
          <Icon name="folder-heroicons-outline" />
          <Icon name="arrow-sm-right-heroicons-outline" />
          <Icon name="folder-heroicons-outline" />
          Merge Categories
        </EventButton>
      </div>
    </div>
    """
  end
end

lib/pan_web/live/category/folllow_or_unfollow_button.ex
defmodule PanWeb.Live.Category.FollowOrUnfollowButton do
  use Surface.LiveComponent
  alias PanWeb.{Follow, Category}
  alias PanWeb.Surface.Icon

  prop(current_user_id, :integer, required: true)
  prop(category, :map, required: true)
  data(following, :boolean, default: false)
  data(followers_count, :integer, default: 0)

  def handle_event("toggle-follow", _params, %{assigns: assigns} = socket) do
    Category.follow(assigns.category.id, assigns.current_user_id)

    socket =
      assign(socket,
        following: !assigns.following,
        category: Category.get_by_id(assigns.category.id),
        followers_count: Category.follows(assigns.category.id)
      )

    {:noreply, socket}
  end

  def render(assigns) do
    following =
      Follow.find_category_follow(assigns.current_user_id, assigns.category.id)
      |> is_nil
      |> Kernel.not()

    assigns =
      assign(assigns,
        following: following,
        followers_count: Category.follows(assigns.category.id)
      )

    ~F"""
    <span>
      {#if @following}
        <button :on-click="toggle-follow"
                class="text-white rounded py-1 px-2 bg-success border border-gray-darker rounded">
          {@followers_count} <Icon name="chat-heroicons-solid"/> Unfollow
        </button>
      {#else}
        <button :on-click="toggle-follow"
                class="text-white rounded py-1 px-2 bg-danger border border-gray-darker rounded">
          {@followers_count} <Icon name="chat-heroicons-outline"/> Follow
        </button>
      {/if}
    </span>
    """
  end
end

lib/pan_web/views/category_view.ex
defmodule PanWeb.CategoryView do
  use PanWeb, :view
end

lib/pan_web/templates/category/_categories.html.eex
<table class="table">
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for category <- @categories do %>
      <%= render "_category_line.html", category: category, conn: @conn, indent: false %>

      <%= unless @no_children do %>
        <%= for child <- category.children do %>
          <%= render "_category_line.html", category: child, conn: @conn, indent: true %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

lib/pan_web/templates/category/_category.html.eex
<ul>
  <li>
    <strong>Title:</strong>
    <%= @category.title %>
  </li>

  <li>
    <strong>Parent:</strong>
    <%= @category.parent_id %>
  </li>
</ul>

<%= link "Show", to: category_path(@conn, :show, @category) %>

lib/pan_web/templates/category/_category_line.html.eex
<tr>
  <td>
    <%= if @indent do %>
      &mdash;&mdash;&nbsp; &nbsp;
    <% end %>
    <%= link @category.title, to: category_path(@conn, :show, @category) %>
  </td>

  <td class="text-right">
    <%= link "Show", to: category_path(@conn, :show, @category), class: "btn btn-default btn-xs" %>
    <%= link "Edit", to: category_path(@conn, :edit, @category), class: "btn btn-default btn-xs" %>
    <%= link "Delete", to: category_path(@conn, :delete, @category),
                       method: :delete,
                       data: [confirm: "Are you sure?"],
                       class: "btn btn-danger btn-xs" %>
  </td>
</tr>

lib/pan_web/templates/category/assign_podcasts.html.eex
<h2>Assigning podcasts to categories</h2>

<div class="row">
  <div class="col-md-3">
    <h3>Select category</h3>
    <div id="category_tree" class="tree"></div>
  </div>

  <div class="col-md-8">
    <h3>Podcasts assigned</h3>
    <table id="assigned_podcasts"
           class="table table-striped table-condensed table-bordered dataTable"
           cellspacing="0"
           width="100%">
    </table>

    <hr/>

    <h3>Podcasts unassigned</h3>
    <table id="unassigned_podcasts"
           class="table table-striped table-condensed table-bordered table-dataTable"
           cellspacing="0"
           width="100%">
    </table>

    <a class="btn btn-primary" onclick="execute_assign()">
      <%= icon "podcast" %>
      <%= icon "arrow-right " %>
      <%= icon "folder-open-heroicons-outlinepen-heroicons-outline-o" %>
      <%= icon "arrow-right " %>
      <%= icon "podcast" %> &nbsp;
      Update Assignments
    </a>
  </div>
</div>

<script>
  $(function() {
    //bootstrap-treeview:  https://github.com/jonmiles/bootstrap-treeview
    var treedata = <%= category_tree(@categories) %>

    $('#category_tree').treeview({
      data: treedata,
      onNodeSelected: function(event, data) { get_podcasts() }
    })

    $('#assigned_podcasts').DataTable({
      serverSide: false,
      data: [{ id: 0,
               title: "Select category first, then select podcasts to remove." +
                      " <kbd>CTRL</kbd> + Click to select several!" }],
      columns: [
        { data: 'id', title: "ID"},
        { data: 'title', title: "Title of podcasts assigned" }
      ],
      select: true
    })

    $('#unassigned_podcasts').DataTable({
      serverSide: false,
      data: [{ id: 0,
               title: "Select category first, then select podcasts to add." +
                      " <kbd>CTRL</kbd> + Click to select several!" }],
      columns: [
        { data: 'title', title: "Title of unassigned podcasts" },
        { data: 'id', title: "ID"}
      ],
      select: true
    })
  })

  function execute_assign(){
    var categoryID = $('#category_tree').treeview('getSelected')[0].categoryId
    var delete_ids = $('#assigned_podcasts').DataTable()
                                            .rows({ selected: true })
                                            .data()
                                            .toArray()
                                            .map(function(podcast) {return podcast.id})
    var add_ids =  $('#unassigned_podcasts').DataTable()
                                            .rows({ selected: true })
                                            .data()
                                            .toArray()
                                            .map(function(podcast) {return podcast.id})

    $.ajax({
      type: "POST",
      url: "<%= category_url(@conn, :execute_assign) %>",
      data: { category_id: categoryID,
              delete_ids: delete_ids,
              add_ids: add_ids},
      headers: {"X-CSRF-TOKEN": "<%= get_csrf_token() %>" },
      success: function(data) {
        get_podcasts()
      }
    })
  }

  function get_podcasts(){
    var categoryID = $('#category_tree').treeview('getSelected')[0].categoryId
    $.ajax({
      url: "/api/categories/" + categoryID + "/get_podcasts",
      success: function (data) {
        $('#assigned_podcasts').dataTable().fnClearTable();
        if (data["podcasts_assigned"].length > 0) {
          $('#assigned_podcasts').dataTable().fnAddData(data["podcasts_assigned"]);
        }
        $('#unassigned_podcasts').dataTable().fnClearTable();
        $('#unassigned_podcasts').dataTable().fnAddData(data["podcasts_unassigned"]);
      }
    })
  }
</script>

lib/pan_web/templates/category/edit.html.eex
<h2>Edit category</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_path(@conn, :update, @category) %>

<%= link "Back", to: category_path(@conn, :index) %>

lib/pan_web/templates/category/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :parent_id, class: "control-label" %>
    <%= text_input f, :parent_id, class: "form-control" %>
    <%= error_tag f, :parent_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/pan_web/templates/category/index.html.eex
<h2>Listing categories</h2>

<p class="text-right">
  <%= link "Merge Categories", to: category_path(@conn, :merge),
                               class: "btn btn-warning" %>
  <%= link "Assign Podcasts to Categories", to: category_path(@conn, :assign_podcasts),
                                            class: "btn btn-primary" %>
</p>

<table id="datatable" class="table table-striped table-condensed table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Parent: Id</th>
      <th>Parent: Title</th>
      <th>Actions</th>
    </tr>
  </thead>
</table>

<script>
  $(function() {
    $('#datatable').DataTable({
      ajax: {
        url: '/admin/categories/datatable',
        dataSrc: 'categories'
      },
      columns: [
        {data: 'id'},
        {data: 'title'},
        {data: 'parent_id'},
        {data: 'parent_title'},
        {data: 'actions'}
      ]
    })
  })
</script>

<%= link "New category", to: category_path(@conn, :new) %>

lib/pan_web/templates/category/merge.html.eex
<h2>Merging categories</h2>

<div class="row">
  <div class="col-md-5">
    <div id="tree1" class="tree"></div>
  </div>
  <div class="col-md-5">
    <div id="tree2" class="tree"></div>
  </div>
  <div class="col-md-2">
    <a class="btn btn-primary" onclick="merge_selected()">
      <%= icon "file-o" %>
      <%= icon "arrow-right " %>
      <%= icon "file-text-o" %>
      Merge Categories
    </a>
  </div>
</div>

<script>
  //bootstrap-treeview:  https://github.com/jonmiles/bootstrap-treeview
  var treedata = <%= category_tree(@categories) %>
  $('#tree1').treeview({data: treedata, showBorder: false});
  $('#tree2').treeview({data: treedata, showBorder: false});

 function merge_selected(){
  var from_id = $("#tree1").treeview('getSelected')[0].categoryId
  var to_id = $("#tree2").treeview('getSelected')[0].categoryId
  window.location = "<%= category_url(@conn, :execute_merge) %>?from=" + from_id + "&to=" + to_id
 }
</script>

lib/pan_web/templates/category/new.html.eex
<h2>New category</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_path(@conn, :create) %>

<%= link "Back", to: category_path(@conn, :index) %>

lib/pan_web/templates/category/show.html.eex
<h2>Show category</h2>

<%= render "_category.html", category: @category, conn: @conn %>
<hr/>
<%= render PanWeb.PodcastView, "_podcast_table.html",
                             podcasts: @category.podcasts,
                             paused: "unknown",
                             stale: "unknown",
                             conn: @conn %>
<hr/>

<%= if @category.parent do %>
  <h1>Parent</h1>
  <%= render "_category.html", category: @category.parent,
                               no_children: true,
                               conn: @conn %>
  <hr/>
<% end %>

<%= if @category.children != [] do %>
  <h1>Children</h1>
  <%= render "_categories.html", categories: @category.children,
                                 no_children: true,
                                 conn: @conn %>
  <hr/>
<% end %>

<%= link "Edit", to: category_path(@conn, :edit, @category) %>
<%= link "Back", to: category_path(@conn, :index) %>