lib/pan_web/router.ex
    live("/personas", Live.Persona.Index, :index, as: :persona_frontend)
    resources("/personas", PersonaFrontendController, only: [:show])

    get("/forgot_password", UserController, :forgot_password)
    post("/request_login_link", UserController, :request_login_link)

    live("/sessions/new", Live.Session.New, :new, as: :session)
    resources("/sessions", SessionController, only: [:create, :delete])
    get("/sessions/login_via_token", SessionController, :login_via_token)
    get("/sessions/login_from_signup", SessionController, :login_from_signup)
    get("/sessions/confirm_email", SessionController, :confirm_email)

    live("/recommendations", Live.Recommendation.Index, :index, as: :recommendation_frontend)

    live("/recommendations/random", Live.Recommendation.Random, :random,
      as: :recommendation_frontend
    )

    get("/vienna-beamers", MaintenanceController, :vienna_beamers)
    get("/2016/:month/:day/:file", MaintenanceController, :blog_2016)
    get("/2017/:month/:day/:file", MaintenanceController, :blog_2017)
    live("/:pid", Live.Persona.Show, :persona, as: :persona_frontend)
  end

  scope "/", PanWeb do
    pipe_through([:browser_minimal_root_layout])

    live("/episodes/:id/player", Live.Episode.Player, :player, as: :episode_frontend)

    live("/podcasts/:id/subscribe_button", Live.Podcast.Subscribe, :subscribe_button,
      as: :podcast_frontend
    )
  end

  scope "/mydata", PanWeb do
    pipe_through([:json_download])

    get("/download", UserJsonDownloadController, :download)
  end

  scope "/pan", PanWeb do
    pipe_through([:browser, :authenticate_user])

    get("/users/payment_info", UserFrontendController, :payment_info)
    post("/users/like_all_subscribed", UserFrontendController, :like_all_subscribed)
    post("/users/follow_all_subscribed", UserFrontendController, :follow_all_subscribed)
    get("/my_podcasts", UserFrontendController, :my_podcasts)
    get("/my_profile", UserFrontendController, :my_profile)
    get("/my_data", UserFrontendController, :my_data)
    delete("/delete_my_account", UserFrontendController, :delete_my_account)

    get("/edit", UserFrontendController, :edit)
    put("/update", UserFrontendController, :update)
    get("/edit_password", UserFrontendController, :edit_password)
    put("/update_password", UserFrontendController, :update_password)
    post("/go_pro", UserFrontendController, :go_pro)

    post("/personas/:id/claim", PersonaFrontendController, :claim)
    get("/personas/:id/warning", PersonaFrontendController, :warning)
    post("/personas/:id/connect", PersonaFrontendController, :connect)
    post("/personas/:id/disconnect", PersonaFrontendController, :disconnect)
    live("/personas/:id/edit", Live.Persona.Edit, :edit, as: :persona_frontend)

    resources("/opmls", OpmlFrontendController, only: [:new, :create, :index, :delete])
    get("/opmls/:id/import", OpmlFrontendController, :import)
    get("/opmls/:id/download", OpmlFrontendController, :download)

    resources("/feed_backlogs", FeedBacklogFrontendController, only: [:new, :create])

    get("/my_recommendations", RecommendationFrontendController, :my_recommendations)
    delete("/my_recommendations/delete_all", RecommendationFrontendController, :delete_all)
    resources("/recommendations", RecommendationFrontendController, only: [:create, :delete])

    delete("/subscriptions/", SubscriptionFrontendController, :delete_all)

    delete("/follows/unfollow_all_categories", FollowFrontendController, :unfollow_all_categories)
    delete("/follows/unfollow_all_personas", FollowFrontendController, :unfollow_all_personas)
    delete("/follows/unfollow_all_podcasts", FollowFrontendController, :unfollow_all_podcasts)
    delete("/follows/unfollow_all_users", FollowFrontendController, :unfollow_all_users)

    delete("/likes/unlike_all_categories", LikeFrontendController, :unlike_all_categories)
    delete("/likes/unlike_all_chapters", LikeFrontendController, :unlike_all_chapters)
    delete("/likes/unlike_all_episodes", LikeFrontendController, :unlike_all_episodes)
    delete("/likes/unlike_all_personas", LikeFrontendController, :unlike_all_personas)
    delete("/likes/unlike_all_podcasts", LikeFrontendController, :unlike_all_podcasts)
    delete("/likes/unlike_all_users", LikeFrontendController, :unlike_all_users)

    delete("/manifestations/delete_all", ManifestationFrontendController, :delete_all)
    resources("/manifestations", ManifestationFrontendController, only: [:delete])
  end

  scope "/moderator", PanWeb do
    pipe_through([:browser, :authenticate_moderator])
    get("/my_moderations", ModerationFrontendController, :my_moderations)
    live("/moderation/:id", Live.Moderation.Moderate, :moderation, as: :moderation_frontend)

    live(
      "/moderation/:id/podcast/:podcast_id/episodes",
      Live.Moderation.EpisodeGrid,
      :episode_grid,
      as: :moderation_frontend
    )

    live("/moderation/:id/podcast/:podcast_id/feeds", Live.Moderation.FeedGrid, :feed_grid,
      as: :moderation_frontend
    )

    live("/moderation/:id/podcast/:podcast_id", Live.Moderation.EditPodcast, :edit_podcast,
      as: :moderation_frontend
    )

    live("/moderation/:id/episode/:episode_id", Live.Moderation.EditEpisode, :edit_episode,
      as: :moderation_frontend
    )

    live("/moderation/:id/feed/:feed_id", Live.Moderation.EditFeed, :edit_feed,
      as: :moderation_frontend
    )
  end

  scope "/pro", PanWeb do
    pipe_through([:browser, :authenticate_pro])

    get("/personas/:id/toggle_delegation", PersonaFrontendController, :toggle_delegation)
    get("/personas/:id/cancel_redirect", PersonaFrontendController, :cancel_redirect)
    get("/personas/:id/redirect", PersonaFrontendController, :redirect)

    get("/invoices/:id/", InvoiceFrontendController, :download)
  end

  scope "/admin", PanWeb do
    pipe_through([:browser, :authenticate_admin, :admin_layout])

    live_dashboard("/dashboard", metrics: PanWeb.Telemetry)
    get("/episodes/remove_duplicates", EpisodeController, :remove_duplicates)

    get(
      "/episodes/remove_javascript_from_shownotes",
      EpisodeController,
      :remove_javascript_from_shownotes
    )

    get("/personas/merge_candidates", PersonaController, :merge_candidates)
    get("/personas/merge_candidate_group", PersonaController, :merge_candidate_group)
    get("/personas/merge", PersonaController, :merge)

    get("/edit_password/:id", UserController, :edit_password)
    put("/update_password/:id", UserController, :update_password)

    get(
      "/users/:user_id/category/:category_id/push_subscriptions",
      UserController,
      :push_subscriptions
    )

    get("/users/merge", UserController, :merge)
    post("/users/execute_merge", UserController, :execute_merge)
    post("/users/:id/unset_pro", UserController, :unset_pro)

    post("/feeds/:id/make_only", FeedController, :make_only)

    post("/alternate_feeds/create_from_backlog", AlternateFeedController, :create_from_backlog)

    live("/categories/merge", Live.Admin.Category.Merge, :merge, as: :category)

    get("/backlog_feeds/subscribe", FeedBacklogController, :subscribe)
    get("/backlog_feeds/subscribe50", FeedBacklogController, :subscribe50)
    get("/backlog_feeds/import_100", FeedBacklogController, :import_100)
    get("/backlog_feeds/:id/import", FeedBacklogController, :import)
    delete("/feed_backlogs/delete_all", FeedBacklogController, :delete_all)
    resources("/backlog_feeds", FeedBacklogController)

    get("/opmls/:id/import", OpmlController, :import)
    live("/opmls", Live.Admin.Opml.Index, :index, as: :opml)
    resources("/opmls", OpmlController, only: [:new, :create, :show, :update, :edit, :delete])

    resources("/invoices", InvoiceController)

    get("/images/cache_missing", ImageController, :cache_missing)
    get("/images/remove_duplicates", ImageController, :remove_duplicates)
    resources("/images", ImageController, only: [:new, :create])

    get("/podcasts/:id/pause", PodcastController, :pause)
    get("/podcasts/:id/touch", PodcastController, :touch)
    get("/podcasts/:id/contributor_import", PodcastController, :contributor_import)
    get("/podcasts/:id/delta_import", PodcastController, :delta_import)
    get("/podcasts/:id/forced_delta_import", PodcastController, :forced_delta_import)
    get("/podcasts/:id/fix_owner", PodcastController, :fix_owner)
    get("/podcasts/:id/unretire", PodcastController, :unretire)
    get("/podcasts/fix_languages", PodcastController, :fix_languages)
    get("/podcasts/:id/update_from_feed", PodcastController, :update_from_feed)
    live("/podcasts/retirement", Live.Admin.Podcast.Retirement, :retirement, as: :podcast)
    live("/podcasts/stale", Live.Admin.Podcast.Stale, :stale, as: :podcast)
    get("/podcasts/orphans", PodcastController, :orphans)
    get("/podcasts/assign_to_unsorted", PodcastController, :assign_to_unsorted)
    get("/podcasts/duplicates", PodcastController, :duplicates)
    get("/podcasts/:id/update_counters/", PodcastController, :update_counters)
    get("/podcasts/update_missing_counters", PodcastController, :update_missing_counters)
    get("/podcasts/update_all_counters", PodcastController, :update_all_counters)
    get("/podcasts/:id/remove_unwanted_references", PodcastController, :remove_unwanted_references)
    get("/podcasts/deprecated", PodcastController, :deprecated)
    resources("/podcasts", PodcastController, only: [:delete])

    get("/search/push_missing", SearchController, :push_missing)
    get("/search/reset_all", SearchController, :reset_all)
    get("/search/delete_orphans", SearchController, :delete_orphans)
    get("/search/migrate", SearchController, :migrate)

    get("/maintenance/stats", MaintenanceController, :stats)
    get("/maintenance/catch_up_thumbnailed", MaintenanceController, :catch_up_thumbnailed)
    get("/maintenance/exception_notification", MaintenanceController, :exception_notification)

lib/pan_web/api/views/invoice_view.ex
defmodule PanWeb.Api.InvoiceView do
  use PanWeb, :view
  use JaSerializer.PhoenixView

  def type(_, _), do: "invoice"

  attributes([:filename, :content_type, :inserted_at])
end

lib/pan_web/controllers/invoice_controller.ex
defmodule PanWeb.InvoiceController do
  use PanWeb, :controller
  alias PanWeb.Invoice

  def index(conn, _params) do
    invoices =
      Repo.all(Invoice)
      |> Repo.preload(:user)

    render(conn, "index.html", invoices: invoices)
  end

  def new(conn, _params) do
    changeset = Invoice.changeset(%Invoice{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"invoice" => invoice_params}) do
    user_id =
      if invoice_params["user_id"] != "",
        do: String.to_integer(invoice_params["user_id"]),
        else: nil

    destination_path =
      if upload = invoice_params["file"] do
        File.mkdir_p("/var/phoenix/pan-uploads/invoices/#{invoice_params["user_id"]}")
        path = "/var/phoenix/pan-uploads/invoices/#{invoice_params["user_id"]}/#{upload.filename}"
        File.cp(upload.path, path)
        path
      else
        ""
      end

    changeset =
      if upload do
        Invoice.changeset(%Invoice{
          content_type: upload.content_type,
          filename: upload.filename,
          path: destination_path,
          user_id: user_id
        })
      else
        Invoice.changeset(%Invoice{
          content_type: nil,
          filename: nil,
          path: destination_path,
          user_id: user_id
        })
      end

    case Repo.insert(changeset) do
      {:ok, _invoice} ->
        conn
        |> put_flash(:info, "Invoice uploaded successfully.")
        |> redirect(to: invoice_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    invoice = Repo.get!(Invoice, id)
    render(conn, "show.html", invoice: invoice)
  end

  def edit(conn, %{"id" => id}) do
    invoice = Repo.get!(Invoice, id)
    changeset = Invoice.changeset(invoice)
    render(conn, "edit.html", invoice: invoice, changeset: changeset)
  end

  def update(conn, %{"id" => id, "invoice" => invoice_params}) do
    invoice = Repo.get!(Invoice, id)
    changeset = Invoice.changeset(invoice, invoice_params)

    case Repo.update(changeset) do
      {:ok, invoice} ->
        conn
        |> put_flash(:info, "Invoice updated successfully.")
        |> redirect(to: invoice_path(conn, :show, invoice))

      {:error, changeset} ->
        render(conn, "edit.html", invoice: invoice, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    invoice = Repo.get!(Invoice, id)

    File.rm(invoice.path)
    Repo.delete!(invoice)

    conn
    |> put_flash(:info, "Invoice deleted successfully.")
    |> redirect(to: invoice_path(conn, :index))
  end
end

lib/pan_web/views/invoice_view.ex
defmodule PanWeb.InvoiceView do
  use PanWeb, :view
end

lib/pan_web/templates/invoice/edit.html.eex
<h2>Edit invoice</h2>

<%= render "form.html", changeset: @changeset,
                        action: invoice_path(@conn, :update, @invoice) %>

<%= link "Back", to: invoice_path(@conn, :index) %>

lib/pan_web/templates/invoice/edit.html.heex
<div class="m-4">
  <h1 class="text-3xl">
    Edit invoice
  </h1>

  <%= render("form.html",
    changeset: @changeset,
    action: invoice_path(@conn, :update, @invoice)
  ) %>

  <%= link("Back",
    to: invoice_path(@conn, :index),
    class: "text-link hover:text-link-dark"
  ) %>
</div>

lib/pan_web/templates/invoice/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <label>Invoice</label>
    <%= file_input f, :file, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :filename, class: "control-label" %>
    <%= text_input f, :filename, class: "form-control" %>
    <%= error_tag f, :filename %>
  </div>

  <div class="form-group">
    <%= label f, :content_type, class: "control-label" %>
    <%= text_input f, :content_type, class: "form-control" %>
    <%= error_tag f, :content_type %>
  </div>

  <div class="form-group">
    <%= label f, :path, class: "control-label" %>
    <%= text_input f, :path, class: "form-control" %>
    <%= error_tag f, :path %>
  </div>

  <div class="form-group">
    <%= label f, :user_id, class: "control-label" %>
    <%= text_input f, :user_id, class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/pan_web/templates/invoice/form.html.heex
<%= form_for @changeset,
         @action,
         [multipart: true, class: "p-4 mb-4 flex flex-col items-start space-y-4"],
         fn f -> %>
  <%= if @changeset.action do %>
    <div class="p-4 border border-danger-dark bg-danger-light/50 rounded-xl mb-4">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="flex flex-col">
    <label>Invoice</label>
    <%= file_input(f, :file) %>
  </div>

  <div class="flex flex-col">
    <%= label(f, :filename) %>
    <%= text_input(f, :filename) %>
    <%= error_tag(f, :filename) %>
  </div>

  <div class="flex flex-col">
    <%= label(f, :content_type) %>
    <%= text_input(f, :content_type) %>
    <%= error_tag(f, :content_type) %>
  </div>

  <div class="flex flex-col">
    <%= label(f, :path) %>
    <%= text_input(f, :path) %>
    <%= error_tag(f, :path) %>
  </div>

  <div class="flex flex-col">
    <%= label(f, :user_id) %>
    <%= text_input(f, :user_id) %>
    <%= error_tag(f, :user_id) %>
  </div>

  <div class="flex flex-col">
    <%= submit("Submit",
      class: "bg-primary hover:bg-primary-light text-white py-2 px-3 rounded-md"
    ) %>
  </div>
<% end %>

lib/pan_web/templates/invoice/index.html.eex
<h2>Listing invoices</h2>

<table class="table">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Content type</th>
      <th>Path</th>
      <th>User Id</th>
      <th>Username</th>
      <th>User Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for invoice <- @invoices do %>
    <tr>
      <td><%= invoice.filename %></td>
      <td><%= invoice.content_type %></td>
      <td><%= invoice.path %></td>
      <td><%= link invoice.user_id, to: user_path(@conn, :show, invoice.user) %></td>
      <td><%= invoice.user.username %></td>
      <td><%= invoice.user.name %></td>

      <td class="text-right">
        <%= link "Show", to: invoice_path(@conn, :show, invoice), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: invoice_path(@conn, :edit, invoice), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: invoice_path(@conn, :delete, invoice), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New invoice", to: invoice_path(@conn, :new) %>

lib/pan_web/templates/invoice/index.html.heex
<div class="m-4">
  <h1 class="text-3xl">Listing invoices</h1>

  <table cellpadding="4" class="my-4">
    <thead>
      <tr>
        <th class="border border-gray-light">
          Filename
        </th>
        <th class="border border-gray-light">
          Content type
        </th>
        <th class="border border-gray-light">
          Path
        </th>
        <th class="border border-gray-light">
          User Id
        </th>
        <th class="border border-gray-light">
          Username
        </th>
        <th class="border border-gray-light">
          User Name
        </th>
        <th class="border border-gray-light"></th>
      </tr>
    </thead>
    <tbody>
      <%= for invoice <- @invoices do %>
        <tr>
          <td class="border border-gray-light">
            <%= invoice.filename %>
          </td>
          <td class="border border-gray-light">
            <%= invoice.content_type %>
          </td>
          <td class="border border-gray-light">
            <%= invoice.path %>
          </td>
          <td class="border border-gray-light">
            <%= link(invoice.user_id, to: databrowser_path(@conn, :show, "user", invoice.user)) %>
          </td>
          <td class="border border-gray-light">
            <%= invoice.user.username %>
          </td>
          <td class="border border-gray-light">
            <%= invoice.user.name %>
          </td>

          <td class="border border-gray-light">
            <%= link("Show",
              to: invoice_path(@conn, :show, invoice),
              class:
                "bg-info text-white border border-gray-dark hover:bg-info-light 
                                                                         inline-block shadow truncate max-w-full py-0.5 px-1 rounded text-sm"
            ) %>
            <%= link("Edit",
              to: invoice_path(@conn, :edit, invoice),
              class:
                "bg-warning text-white border border-gray-dark hover:bg-warning-light 
                                                                         inline-block shadow truncate max-w-full py-0.5 px-1 rounded text-sm"
            ) %>
            <%= link("Delete",
              to: invoice_path(@conn, :delete, invoice),
              method: :delete,
              data: [confirm: "Are you sure?"],
              class:
                "bg-danger text-white border border-gray-dark hover:bg-danger-light 
                                                                           inline-block shadow truncate max-w-full py-0.5 px-1 rounded text-sm"
            ) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link("New invoice",
    to: invoice_path(@conn, :new),
    class: "text-link hover:text-link-dark"
  ) %>
</div>

lib/pan_web/templates/invoice/new.html.eex
<h2>New invoice</h2>

<%= render "form.html", changeset: @changeset,
                        action: invoice_path(@conn, :create) %>

<%= link "Back", to: invoice_path(@conn, :index) %>

lib/pan_web/templates/invoice/new.html.heex
<div class="m-4">
  <h1 class="text-3xl">
    New invoice
  </h1>

  <%= render("form.html",
    changeset: @changeset,
    action: invoice_path(@conn, :create)
  ) %>

  <%= link("Back",
    to: invoice_path(@conn, :index),
    class: "text-link hover:text-link-dark"
  ) %>
</div>

lib/pan_web/templates/invoice/show.html.eex
<h2>Show invoice</h2>

<ul>

  <li>
    <strong>Filename:</strong>
    <%= @invoice.filename %>
  </li>

  <li>
    <strong>Content type:</strong>
    <%= @invoice.content_type %>
  </li>

  <li>
    <strong>Path:</strong>
    <%= @invoice.path %>
  </li>

  <li>
    <strong>User:</strong>
    <%= @invoice.user_id %>
  </li>

</ul>

<%= link "Edit", to: invoice_path(@conn, :edit, @invoice) %>
<%= link "Back", to: invoice_path(@conn, :index) %>

lib/pan_web/templates/invoice/show.html.heex
<div class="m-4">
  <h1 class="text-3xl">
    Show invoice
  </h1>

  <ul class="m-4">
    <li>
      <strong>Filename:</strong>
      <%= @invoice.filename %>
    </li>

    <li>
      <strong>Content type:</strong>
      <%= @invoice.content_type %>
    </li>

    <li>
      <strong>Path:</strong>
      <%= @invoice.path %>
    </li>

    <li>
      <strong>User:</strong>
      <%= @invoice.user_id %>
    </li>
  </ul>

  <%= link("Edit",
    to: invoice_path(@conn, :edit, @invoice),
    class: "text-link hover:text-link-dark"
  ) %>
  <%= link("Back",
    to: invoice_path(@conn, :index),
    class: "text-link hover:text-link-dark"
  ) %>
</div>